data_dir: data
gnss/ins: gins_sync
data_mask_path: data_mask.txt

gins_installation_height: 0.0

# Algorithm parameter configuration
optimization_params:
  # Number of threads for optimizer
  num_threads: 4
  
  # First stage optimization (LiDAR-GNSS/INS)
  lidar_gins_optimization:
    max_iterations: 20
    max_correspondence_distance: 0.5
  
  # Second stage optimization (Multi-LiDAR)
  multi_lidar_optimization:
    max_iterations: 30
    max_correspondence_distance: 0.5
  
  # Keyframe selection parameters
  keyframe_selection:
    # Rotation threshold (radians)
    rotation_threshold: 0.6
    # Translation threshold (meters)
    translation_threshold: 5.0
  
  # Output format parameters
  output:
    # Time display precision (decimal places)
    time_precision: 3
    # Millisecond to second conversion factor
    time_scale_factor: 1000.0
    # Output file path for extrinsic parameters
    extrinsic_output_file: "output/extrinsic_parameters.txt"
  
  # Point cloud processing parameters
  point_cloud:
    # Voxel grid size for downsampling
    voxel_size: 0.2
    # Downsampling leaf size
    downsample_leaf_size: 0.1
    # Ground segmentation distance threshold
    ground_distance_threshold: 0.1
    
  # Correspondence parameters
  correspondence:
    # Distance threshold for correspondences
    distance_threshold: 1.0
    
  # Noise model parameters
  noise_model:
    # Huber robust estimator parameter
    huber_parameter: 0.1
    # Rotation standard deviation
    rotation_std: 0.01
    # Translation standard deviation  
    translation_std: 0.01

lidar_list:
  - livox
  - middle
  - left
  - right
  - back
#  - ouster
#  - front_left
#  - front_right
#  - avia
#  - velo

# T_imu_lidar
init_ext:
  livox:
   position:
     x: 0
     y: 0
     z: 0
   orientation:
     w: 0.99
     x: 0.01
     y: -0.12
     z: -0.01
  middle:
   position:
     x: 0
     y: 0
     z: 0
   orientation:
     w: 0.653126
     x: -0.0287627
     y: 0.75669
     z: 0.00441556
  right:
   position:
     x: 0
     y: 0
     z: 0
   orientation:
     w: 0.494543
     x: 0.470428
     y: 0.527599
     z: -0.505732
  left:
   position:
     x: 0
     y: 0
     z: 0
   orientation:
     w: -0.480985
     x: 0.504621
     y: -0.503708
     z: -0.510186
  back:
   position:
     x: 0
     y: 0
     z: 0
   orientation:
     w: 0.0400058
     x: -0.6901037
     y: -0.0600087
     z: 0.7201079

  ouster:
   position:
     x: 0
     y: 0
     z: 0
   orientation:
     w: 1
     x: 0
     y: 0
     z: 0

  front_left:
    position:
      x: 0
      y: 0
      z: 0
    orientation:
      w: 0.705534
      x: 0.0335795
      y: 0.00638963
      z: 0.707852

  front_right:
    position:
      x: 0
      y: 0
      z: 0
    orientation:
      w: 0.715456
      x: -0.0315438
      y: -0.0502189
      z: 0.696136

  avia:
    position:
      x: 0
      y: 0
      z: 0
    orientation:
      w: 0.00
      x: -0.00
      y: -0.00
      z: 1.00

  velo:
    position:
      x: 0
      y: 0
      z: 0
    orientation:
      w: 0.97
      x: 0.00
      y: 0.26
      z: 0.00